### ISSUE TITLE
Pessoas Jurídicas precisam de impostos destacados.

### ISSUE THREAD

**Issue by jaysoifer** [claudiosanches/woocommerce-boleto#57]
Boa tarde,

Dentre nossos clientes PJ temos uma empresa que presta serviços de consultoria e treinamento para outras empresas (B2B).

Este nosso cliente afirma que recentemente tornou-se obrigatório destacar os impostos na emissão do boleto, ou seja:

Boletos com valores até R$ 666,65, deverão constar os seguintes recolhimentos:
PIS 0,65%  Cofins 3%  CSLL 1%

Boletos com valores a partir de R$ 666,66, deverão constar os seguintes recolhimentos:
IR 1,5%  PIS 0,65%   Cofins 3% CSLL 1%

_Compreendo que isso não é uma necessidade de "todos" os usuários do plugin..._

Estou considerando adequar o plugin e fazer o Pull Request: isto se tornaria uma opção a mais para os usuários.

_Caso eu venha a desenvolver esse código, existe interesse em incluir isso no plugin?_ ou seja, vale a pena preparar um Pull Request para isso?

**Comment by claudiosmweb** [comment]
Por favor, pode enviar o Pull Request.
