### ISSUE TITLE
Separar digito do "Nosso Numero"

### ISSUE THREAD

**Issue by GuilhermeCWB90** [claudiosanches/woocommerce-boleto#62]
Olá!

Estou configurando o sistema para o boleto da Caixa Econômica, para homologar os 20 boletos que eles pedem preciso separar o último digito do item "Nosso Número" do boleto. 

No boleto feito aparece assim (tudo junto):
Nosso número 140000000000045247

Preciso que o número 7 seja separado do restante para proceder com a homologação
ficando assim:
Nosso número 14000000000004524-7

Gostaria de saber se alguém teve que modificar isto, e como foi o processo para faze-lo ? Estou tendo dificuldades nesta parte, gostaria por gentileza de ajuda.

Muito Obrigado!

**Comment by paulop** [comment]
Sim é preciso fazer.
no arquivo 
https://github.com/claudiosanches/woocommerce-boleto/blob/master/includes/banks/cef/layout.php

mude na linha 208 e 701
de
`<?php echo $dadosboleto["nosso_numero"]?>`
para
`<?php echo substr($dadosboleto["nosso_numero"], 0, -1).'-'.substr($dadosboleto["nosso_numero"], -1)?>`

@GuilhermeCWB90 
antes tarde do que nunca neh? rsrs

**Comment by GuilhermeCWB90** [comment]
Já consegui resolver este problema.

Mas muito obrigado pela atenção !
