### ISSUE TITLE
Aparecendo um C no código 

### ISSUE THREAD

**Issue by arthurbonora** [claudiosanches/woocommerce-boleto#67]
Olá, no código do boleto santander está aparecendo um C. 
Tem algum bug a corrigir?

Segue print: http://prntscr.com/c4n6as

**Comment by claudiosmweb** [comment]
Talvez algo na sua configuração, porque pelo o código não consigo ver nada que iria gerar esse C: 
https://github.com/claudiosmweb/woocommerce-boleto/blob/master/includes/banks/santander/functions.php

**Comment by arthurbonora** [comment]
blz, obrigado
