### ISSUE TITLE
Boleto registrado

### ISSUE THREAD

**Issue by jerfeson** [claudiosanches/woocommerce-boleto#69]
Está previsto alteração do plugin para boleto registrado ?

**Comment by claudiosanches** [comment]
Não, a partir de janeiro vou remover este plugin do repositório do WordPress.

**Comment by jerfeson** [comment]
Claudio, será desenvolvido um novo plugin, ou não é possível realizar essa implementação no wordpress/woocommecerce ? Saberia dizer

**Comment by claudiosanches** [comment]
Porque não funcionaria no WordPress ou WooCommerce?
E não existe "Alterar", existe criar do zero com a API dos bancos.
No momento tem plugin do Itau Shopline e estou fazendo do Bradesco e BB.

**Comment by jerfeson** [comment]
Obrigado Claudio pelas informações. Bom trabalho pra você.
