### ISSUE TITLE
Funcionamento para clientes Itaú

### ISSUE THREAD

**Issue by castropablo** [claudiosanches/woocommerce-boleto#70]
Olá Claudio.
Tenho conta pessoal no banco Itaú e, por este motivo, não consigo utilizar o WooCommerce Itau Shopline conforme você recomenda. (O Shopline exige conta empresarial)
Neste caso, é possível usar o Woocommerce boleto?
O Woocommerce Boleto vai conseguir emitir um boleto?
Muito obrigado!

**Comment by claudiosanches** [comment]
Até onde eu sei só é possível emitir boletos se tiver conta empresarial.
Além disso vai precisar usar o Shopline, já que todos os boletos agora vão precisar ser registrados.
