### ISSUE TITLE
Ao clicar em PAGAR BOLETO a página não abre. Erro 404

### ISSUE THREAD

**Issue by marcelocor** [claudiosanches/woocommerce-boleto#73]
Instalei o plugin e configurei pra o Bancoob.
Ao clicar em PAGAR BOLETO a página não abre. Erro 404.
Instalei depois o plugin que converte pra pdf, mas também deu o mesmo erro.
As configurações estão corretas. 
O que devo fazer pra funcionar?

Obrigado.
MARCELO CORRÊA

**Comment by claudiosanches** [comment]
Melhorar parar de utilizar este plugin, vou remover ele do repositório do WordPress em breve.
